let v=[{img:"https://images-eu.ssl-images-amazon.com/images/I/41hl75HtNGL.jpg",ItemText:"How to Raise a Boy",Price:1444
},{img:"https://images-eu.ssl-images-amazon.com/images/I/61Ioe%2BT%2B1qL.jpg",ItemText:"Zulus at War: The History, Rise, and Fall of the Tribe That Washed Its Spears",Price:790.23},{img:"https://images-eu.ssl-images-amazon.com/images/I/51-UzqjPNfL.jpg",ItemText:"Stoic Lessons: Musonius Rufus' Complete Works: Volume 6 (Stoicism in Plain English)",Price:798},{img:"https://images-eu.ssl-images-amazon.com/images/I/51G-XziI4gL.jpg",ItemText:"One Thousand Familiar Phrases in English and Romanized Japanese (Classic Reprint)",Price:669
},{img:"https://images-eu.ssl-images-amazon.com/images/I/61vvsKiGp4L.jpg",ItemText:"Stories for Boys Who Dare to be Different 2",Price:674},{img:"https://images-eu.ssl-images-amazon.com/images/I/51hSy1MDmTL.jpg",ItemText:"Self Assessment and Review of Biochemistry",Price:653},{img:"https://images-eu.ssl-images-amazon.com/images/I/51M%2BanIme5L.jpg",ItemText:"Gurudeva - Hindi",Price:254},{img:"https://images-eu.ssl-images-amazon.com/images/I/51IxobbR9OL.jpg",ItemText:"The Death of Expertise: The Campaign against Established Knowledge and Why it Matters",Price:933},{img:"https://images-eu.ssl-images-amazon.com/images/I/51grcCx39fL.jpg",ItemText:"Optimal Transport Methods in Economics",Price:2496
},{img:"https://images-eu.ssl-images-amazon.com/images/I/510fuB3gg%2BL.jpg",ItemText:"KP SALES chu chu Todler baby kids bath toys non-toxic animal shapes sound like chu chu toys set of 15 piece, Assorted Color & Shapes, Learning & Educating about Animals & sound",Price:245},{img:"https://images-eu.ssl-images-amazon.com/images/I/31FfEtfx20L.jpg",ItemText:"Q&A a Day for the Soul: 365 Questions, 5 Years, 1,825 Answers",Price:976
},{img:"https://images-eu.ssl-images-amazon.com/images/I/61brO5VXAOL.jpg",ItemText:"Conservation from the Margins",Price:731},{img:"https://images-eu.ssl-images-amazon.com/images/I/31UmzEgdNyL.jpg",ItemText:"Big Brother",Price:2425},
{img:"https://images-eu.ssl-images-amazon.com/images/I/41meLv2x6sL.jpg",ItemText:"Tubby Craft Dye Ink Pad – Color: Hot Pink",Price:250},
{img:"https://images-eu.ssl-images-amazon.com/images/I/41AY3qqN9tL.jpg",ItemText:"The Little Book of Everything",Price:156.18},{img:"https://images-eu.ssl-images-amazon.com/images/I/51vvkntCTvL.jpg",ItemText:"Hyra Express Disney 12pcs/Set Kung fu Panda Shrek Madagascar Toys PVC Action Figures Movies & TV Toys Kids Toys Gifts for Children",Price:1247},{img:"https://images-eu.ssl-images-amazon.com/images/I/51I-c9i7cpL.jpg",ItemText:"Techno Buzz Deal 20 Activities & Games Fun Laptop Notebook Computer Toy for Kids",Price:899},{img:"https://images-eu.ssl-images-amazon.com/images/I/51QCklDibGL.jpg",ItemText:"Bad Guys Episode 6: Alien vs Bad Guys",Price:194},{img:"https://images-eu.ssl-images-amazon.com/images/I/51WzFhBA9gL.jpg",ItemText:"Ethical Hacking for Beginners: How to Build Your Pen Test Lab Fast",Price:819},{img:"https://images-eu.ssl-images-amazon.com/images/I/51oiQ6bwM%2BL.jpg",ItemText:"Short Stories in German for Beginners: Read for pleasure at your level, expand your vocabulary and learn German the fun way! (Foreign Language Graded Reader Series)",Price:829},{img:"https://images-eu.ssl-images-amazon.com/images/I/51gzCaKKRaL.jpg",ItemText:"Class 8: Work Book & Reasoning Book Combo for NSO-IMO-IEO-NCO-IGKO (2018-19)",Price:405},{img:"https://images-eu.ssl-images-amazon.com/images/I/41%2BLwdRCZRL.jpg",ItemText:"Authentic Leadership (Emotional Intelligence Series) (HBR Emotional Intelligence)",Price:259},{img:"https://images-eu.ssl-images-amazon.com/images/I/51-RtFH18YL.jpg",ItemText:"Dodo Mini Acad-Pad 2018-2019 Pocket Mid Year Diary, Academic Year, Week to View: A mid-year diary-doodle-memo-message-engagement-calendar-organiser-planner book for students & teachers",Price:898},{img:"https://images-eu.ssl-images-amazon.com/images/I/41dQBI5gY3L.jpg",ItemText:"Only the Best Will Do: The compelling case for investing in quality growth businesses",Price:2016},
{img:"https://images-eu.ssl-images-amazon.com/images/I/51aWQHdRWpL.jpg",ItemText:"French B for the IB Diploma Second Edition",Price:2536},{img:"https://images-eu.ssl-images-amazon.com/images/I/41nWxhji%2BgL.jpg",ItemText:"Miconazole: Treatment of Fungal Infection Like (Oral Thrush, Vaginal Candidiasis)",Price:689},{img:"https://images-eu.ssl-images-amazon.com/images/I/41h8qJ1TxiL.jpg",ItemText:"ICET Complete Reference",Price:230},{img:"https://images-eu.ssl-images-amazon.com/images/I/51Yx2AC1%2B1L.jpg",ItemText:"Paleomicrobiology of Humans (ASM Books)",Price:4242.09},
{img:"https://images-eu.ssl-images-amazon.com/images/I/51IQMlz6TLL.jpg",ItemText:"Objective NCERT at your FINGERTIPS for NEET-AIIMS - Biology",Price:622},{img:"https://images-eu.ssl-images-amazon.com/images/I/41Emb3BTR%2BL.jpg",ItemText:"CBSE Sample Question Papers Class 10 Mathematics (For February 2020 Exam)",Price:110
},{img:"https://images-eu.ssl-images-amazon.com/images/I/415hM-Jp1qL.jpg",ItemText:"Faster, Fewer, Better Emails: Manage the Volume, Reduce the Stress, Love the Results",Price:850},{img:"https://images-eu.ssl-images-amazon.com/images/I/41UIdrkv5JL.jpg",ItemText:"Gaza – An Inquest into Its Martyrdom",Price:1679},
{img:"https://images-eu.ssl-images-amazon.com/images/I/51a%2B-IyfxcL.jpg",ItemText:"Design and Analysis of Connections in Steel Structures: Fundamentals and Examples",Price:3957},{img:"https://images-eu.ssl-images-amazon.com/images/I/41fRRyRkLXL.jpg",ItemText:"The Ministry of Truth: A Biography of George Orwell's 1984",Price:461.23},{img:"https://images-eu.ssl-images-amazon.com/images/I/51Zrs3AlgaL.jpg",ItemText:"Piero and Gloria Cicionesi",Price:2004.5},{img:"https://images-eu.ssl-images-amazon.com/images/I/411fl-P6FIL.jpg",ItemText:"Chicago Price Theory",Price:3447},
{img:"https://images-eu.ssl-images-amazon.com/images/I/41PPY6v3WoL.jpg",ItemText:"Dr. Pestana's Surgery Notes: Top 180 Vignettes for the Surgical Wards (Kaplan Test Prep)",Price:1863
},{img:"https://images-eu.ssl-images-amazon.com/images/I/51zNrvMMdmL.jpg",ItemText:"Clinical Biochemistry: An Illustrated Colour Text, 6e",Price:2195},{img:"https://images-eu.ssl-images-amazon.com/images/I/41fMkflSecL.jpg",ItemText:"Winning by Resting",Price:734},{img:"https://images-eu.ssl-images-amazon.com/images/I/41zczY6GrjL.jpg",ItemText:"Think and Go Green",Price:155}]

v.forEach(function(elem){
    let div = document.createElement("div")
    document.querySelector(".container1").append(div)
    let img = document.createElement("img")
    img.setAttribute("src",elem.img)
    let p1 = document.createElement("p")
    p1.innerText=elem.ItemText
    let p2 = document.createElement("p")
    p2.innerText=elem.Price
    let hr = document.createElement("hr")
    let div1 = document.createElement("div")
    let p3 = document.createElement("p")
    p3.innerText="View Now"
    let p4 = document.createElement("p")
    p4.innerText="More details"
    div1.append(p3,p4)
    div.append(img,p1,p2,hr,div1)
})